name: 推送每日一句图

on:
  schedule:
    - cron: '00 12 * * *'
  watch:
    types: [started]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
         
      - name: 'Install requirements'
        run: pip install -r ./requirements.txt 
        
      - name: '图文消息' 
        run: python3 ./src/img.py
        env:
            TZ: Asia/Shanghai
            SKEY: ${{ secrets.SKEY }}     #Qmsg通知
            #XMLY_SPEED_COOKIE: ${{ secrets.XMLY_SPEED_COOKIE }}  #必须
            # XMLY_ACCUMULATE_TIME: ${{ secrets.XMLY_ACCUMULATE_TIME }} #非私密信息，去掉
            #BARK: ${{ secrets.BARK }}     # bark服务
            urlSKEY: ${{ secrets.urlSKEY }}   # 企业机器人酱服务
            #TG_BOT_TOKEN: ${{secrets.TG_BOT_TOKEN}} # tg通知token
            #TG_USER_ID:  ${{secrets.TG_USER_ID}}    # tg通知id
            boturl: ${{ secrets.boturl}}
